// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StreetNameRegistry.Api.BackOffice;

namespace StreetNameRegistry.Api.BackOffice.Migrations
{
    [DbContext(typeof(BackOfficeContext))]
    [Migration("20220310140341_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StreetNameRegistry.Api.BackOffice.MunicipalityIdByPersistentLocalId", b =>
                {
                    b.Property<int>("PersistentLocalId")
                        .HasColumnType("int");

                    b.Property<Guid>("MunicipalityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PersistentLocalId")
                        .IsClustered();

                    b.ToTable("MunicipalityIdByPersistentLocalId", "StreetNameRegistryBackOffice");
                });
#pragma warning restore 612, 618
        }
    }
}
